### ISSUE TITLE
Feature wish: exclude path(s) from link check

### ISSUE THREAD

**Issue by deining** [untitaker/hyperlink#162]
`hyperlink` is a great , thanks for providing this useful tool!
Is there any way to exclude certain path from link check? I envision something like a `IgnoreDirs` setting where you can specify an array of regexs of directories to ignore when scanning for HTML files.

**Comment by untitaker** [comment]
There is currently no way at all. I believe that would be feasible to add but I would like to keep support for this sort of thing as simple as possible.

One way to achieve that would possibly be to allow multiple directories as arguments, then people can run hyperlink $(find . -type dir | grep -v badDirectory) or something like that

**Comment by untitaker** [comment]
Actually, `rg --files -thtml | rg -v badDirectory | hyperlink --stdin` is probably what one wants

There is however further complication. If a particular HTML file is not scanned, it means that it is also not recognized as a valid link in HTML files that do end up being scanned. I am not sure if that is intuitive behavior.

I'd certainly welcome patches that try and prototype the design.

Out of curiosity, why do you need this option in your particular case? Is hyperlink too slow otherwise or do you want to ignore certain errors? Could it be that those errors are bugs in hyperlink?

**Comment by deining** [comment]
> Out of curiosity, why do you need this option in your particular case?

I do have broken links in my page that result from the site generator. This issue is fixed upstream, but not rolled out yet.

> Is hyperlink too slow otherwise

No, not at all.

> or do you want to ignore certain errors?

Yes, I want to ignore certain errors until the fix is rolled out.

> Could it be that those errors are bugs in hyperlink?

No, certainly not. The reported links are broken, indeed.

I hope that makes my motivation clear.
