### ISSUE TITLE
upgrade clap, or move away from it

### ISSUE THREAD

**Issue by untitaker** [untitaker/hyperlink#176]
clap 4.0 is out, and hyperlink is out of date

however, clap 5.0 seems to be around the corner as well

should we just move to the `argh` crate? I'm a big sucker for binary size, and the amount of dependencies and upgrading churn added by clap is starting to piss me off

so many questions

**Comment by oylenshpeegul** [comment]
I've been a fan of clap's derive interface since it was called structopt. I had never heard of argh before seeing this ticket, so I decided to have a look.  I made branch for each

https://github.com/oylenshpeegul/hyperlink/tree/clap-v4

https://github.com/oylenshpeegul/hyperlink/tree/argh

Changing from clap 3 to 4 wasn't too bad. Let's hope changing to clap 5 will be even easier.

**Comment by untitaker** [comment]
neat. what's the release binary size?

**Comment by oylenshpeegul** [comment]
❯ ls -lh target/release/hyperlink
-rwxr-xr-x 2 tim tim 1.9M Oct 28 15:21 target/release/hyperlink

**Comment by oylenshpeegul** [comment]
Not much of a difference on my machine

argh
❯ ls -lh target/release/hyperlink
-rwxr-xr-x 2 tim tim 1.9M Oct 28 15:21 target/release/hyperlink

clap-v4
❯ ls -lh target/release/hyperlink
-rwxr-xr-x 2 tim tim 2.2M Oct 28 15:27 target/release/hyperlink

clap-v3
❯ ls -lh target/release/hyperlink
-rwxr-xr-x 2 tim tim 2.2M Oct 28 15:29 target/release/hyperlink

**Comment by untitaker** [comment]
a win is a win, feel free to make a PR for argh, for as long as the output is roughly the same and the CLI doesn't have breaking changes
