### ISSUE TITLE
Support for links without .html extension

### ISSUE THREAD

**Issue by jmfury** [untitaker/hyperlink#95]
👋  Hyperlink is really an awesome tool, so first off, thanks for putting this out there!

I wondered if it would be possible to support an opt out of the strictness regarding `.html` extensions on links - these are essentially false positives in my case 

Example: `/about` is an error but `/about.html` does exist (checking against Next.js build dir)

I'm not sure how common clean internal URL links are among static site generators but my guess is it might be a useful option

**Comment by untitaker** [comment]
I don't know nextjs, so bear with me. How are you able to serve /about with nginx or gh pages if nextjs produces about.html?

**Comment by jmfury** [comment]
> I don't know nextjs, so bear with me. How are you able to serve /about with nginx or gh pages if nextjs produces about.html?

Honestly not positive, I don't use `nginx` or gh pages ... so bear with _me_ there 😅   - Next.js will produce static html files in a couple ways, in either case the files are able to be served with a static file server (something like [serve](https://github.com/vercel/serve) - common way to serve locally at least) or used by Next.js own server (dynamic mode) of course (e.g. on Vercel)

In this case I'm basically just trying to scan the output of `next build` (`.next/server/pages` where statically generated `.html` files are at. Running this in context of a GitHub (action) workflow so for me serving the site is kind of irrelevant, it's mainly just get the results out of `hyperlink` for PRs

**Comment by untitaker** [comment]
Then you need to find a way to generate a static site from nextjs that can be served on those platforms in order to use hyperlink. I think the build dir you're pointing it to is not that. I did a quick search and it seems the export command for next does that.

Hyperlink will not support this random proprietary/internal build dir, that's a moving target and not close to even being an ad-hoc standard. Based on your description I doubt it even contains all data necessary to serve the site. If you think it could work with small adjustments you can fork hyperlink but I don't want to maintain that.

**Comment by jmfury** [comment]
👍  Sounds good, thank you!
